// Generated by CoffeeScript 1.9.3
module.exports = function(robot) {
  robot.respond(/ol(á|a)/i, function(res) {
    return res.send("Olá");
  });
  return robot.hear(/I like pie/i, function(res) {
    return res.emote("makes a freshly baked pie");
  });
};
